"""Canonical 66-book registry for the Bíblia cockpit.

Each book carries multilingual aliases (PT/ES/EN and common abbreviations,
normalized by the passage parser) plus conservative introductory facts
(authorship, date, occasion) aligned with broad evangelical consensus.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.schemas.bible import BookProfile


@dataclass(frozen=True, slots=True)
class Book:
    code: str
    name_pt: str
    testament: str
    genre: str
    aliases: tuple[str, ...]
    author: str
    date: str
    occasion: str


BOOKS: tuple[Book, ...] = (
    Book("GEN", "Gênesis", "AT", "Pentateuco",
         ("Gênesis", "Génesis", "Genesis", "Gen", "Gn", "Bereshit"),
         "Moisés (tradição mosaica, fontes antigas)",
         "Conteúdo ≈ séc. XV–XIII a.C.; forma final pós-exílica",
         "Origens: criação, queda, juízo e promessa; aliança com Abraão e a família patriarcal."),
    Book("EXO", "Êxodo", "AT", "Pentateuco",
         ("Êxodo", "Éxodo", "Exodo", "Ex", "Shemot"),
         "Moisés",
         "≈ séc. XV–XIII a.C.",
         "Libertação do Egito, aliança no Sinai e instituição do culto e da lei."),
    Book("LEV", "Levítico", "AT", "Pentateuco",
         ("Levítico", "Levítico", "Lev", "Lv", "Vayikra"),
         "Moisés",
         "≈ séc. XV–XIII a.C.",
         "Santidade de Deus e do povo: sacrifícios, sacerdócio e pureza ritual."),
    Book("NUM", "Números", "AT", "Pentateuco",
         ("Números", "Números", "Numeros", "Num", "Nm", "Bemidbar"),
         "Moisés",
         "≈ séc. XV–XIII a.C.",
         "Peregrinação no deserto: censos, provações e preparação para entrar em Canaã."),
    Book("DEU", "Deuteronômio", "AT", "Pentateuco",
         ("Deuteronômio", "Deuteronomio", "Dt", "Deu", "Devarim"),
         "Moisés (com epílogo posterior)",
         "≈ séc. XV–XIII a.C.; forma final posterior",
         "Discursos de Moisés às portas de Canaã: renovação da aliança e amor a Deus."),
    Book("JOS", "Josué", "AT", "Histórico",
         ("Josué", "Josue", "Joshua", "Js", "Jos"),
         "Josué (tradição; com acréscimos)",
         "≈ séc. XIV–XII a.C.",
         "Conquista e distribuição da terra de Canaã, cumprindo as promessas a Abraão."),
    Book("JDG", "Juízes", "AT", "Histórico",
         ("Juízes", "Jueces", "Juizes", "Jz", "Jdg"),
         "Autor desconhecido (tradição profética)",
         "≈ séc. XI–X a.C. (conteúdo)",
         "Ciclos de apostasia e livramento pelos juízes; 'cada um fazia o que parecia reto'."),
    Book("RUT", "Rute", "AT", "Histórico",
         ("Rute", "Rut", "Ruth", "Rt"),
         "Autor desconhecido",
         "Período dos juízes; compilado depois",
         "Lealdade e redenção de uma moabita; linhagem de Davi."),
    Book("1SA", "1 Samuel", "AT", "Histórico",
         ("1 Samuel", "I Samuel", "1Sa", "1samuel", "1 samuel"),
         "Samuel e profetas (tradição)",
         "≈ séc. X a.C. (conteúdo)",
         "Transição dos juízes à monarquia: Samuel, Saul e a unção de Davi."),
    Book("2SA", "2 Samuel", "AT", "Histórico",
         ("2 Samuel", "II Samuel", "2Sa", "2samuel", "2 samuel"),
         "Natã/Gade (tradição davídica)",
         "≈ séc. X a.C.",
         "Reinado de Davi: aliança davídica, pecado e restauração."),
    Book("1KI", "1 Reis", "AT", "Histórico",
         ("1 Reis", "I Reyes", "1Rs", "1reis", "1 reis", "1Re"),
         "Autor desconhecido (escola deuteronomista)",
         "≈ séc. VI a.C. (compilação)",
         "Salomão, o templo e a divisão do reino; ministério de Elias."),
    Book("2KI", "2 Reis", "AT", "Histórico",
         ("2 Reis", "II Reyes", "2Rs", "2reis", "2 reis", "2Re"),
         "Autor desconhecido (escola deuteronomista)",
         "≈ séc. VI a.C. (compilação)",
         "Declínio dos reinos, ministério de Eliseu e o exílio babilônico."),
    Book("1CH", "1 Crônicas", "AT", "Histórico",
         ("1 Crônicas", "I Crónicas", "1Cr", "1cronicas", "1 cronicas", "1Ch"),
         "Esdras (tradição do cronista)",
         "≈ séc. V–IV a.C.",
         "Genealogias e reinado de Davi: o templo e a esperança davídica pós-exílica."),
    Book("2CH", "2 Crônicas", "AT", "Histórico",
         ("2 Crônicas", "II Crónicas", "2Cr", "2cronicas", "2 cronicas", "2Ch"),
         "Esdras (tradição do cronista)",
         "≈ séc. V–IV a.C.",
         "História dos reis de Judá e do templo até o decreto de Ciro."),
    Book("EZR", "Esdras", "AT", "Histórico",
         ("Esdras", "Ezra", "Ed", "Esd"),
         "Esdras",
         "≈ séc. V a.C.",
         "Retorno do exílio e restauração do templo e da comunidade."),
    Book("NEH", "Neemias", "AT", "Histórico",
         ("Neemias", "Nehemías", "Neh", "Ne"),
         "Neemias (com material de Esdras)",
         "≈ séc. V a.C.",
         "Reconstrução dos muros de Jerusalém e reformas da comunidade."),
    Book("EST", "Ester", "AT", "Histórico",
         ("Ester", "Ester", "Est", "Et"),
         "Autor desconhecido",
         "≈ séc. V–IV a.C.",
         "Preservação dos judeus na Pérsia; a providência oculta de Deus."),
    Book("JOB", "Jó", "AT", "Poético/Sapiencial",
         ("Jó", "Job", "Jb"),
         "Autor desconhecido",
         "Antigo; forma canônica posterior",
         "O sofrimento do justo: soberania de Deus e o valor do temor a Ele."),
    Book("PSA", "Salmos", "AT", "Poético/Sapiencial",
         ("Salmos", "Salmo", "Sal", "Sl", "Ps"),
         "Davi e outros salmistas",
         "Séc. X–V a.C.",
         "Hinário do culto: louvor, lamento, confissão e esperança messiânica."),
    Book("PRO", "Provérbios", "AT", "Poético/Sapiencial",
         ("Provérbios", "Proverbios", "Pv", "Pr", "Pro"),
         "Salomão e sábios de Israel",
         "Séc. X–VI a.C.",
         "Sabedoria prática: o temor do Senhor é o princípio do conhecimento."),
    Book("ECC", "Eclesiastes", "AT", "Poético/Sapiencial",
         ("Eclesiastes", "Eclesiastés", "Ec", "Ecl", "Qohelet"),
         "O 'Pregador' (tradição salomônica)",
         "≈ séc. X–V a.C.",
         "Futilidade da vida sem Deus; temer a Deus e guardar seus mandamentos."),
    Book("SNG", "Cantares", "AT", "Poético/Sapiencial",
         ("Cantares", "Cânticos", "Cantares de Salomão", "Cântico dos Cânticos",
          "Cantico de los Cantares", "Ct", "Song of Solomon", "SNG", "Cant"),
         "Salomão (tradição)",
         "≈ séc. X a.C.",
         "Poema do amor conjugal; imagem do amor de Deus por seu povo."),
    Book("ISA", "Isaías", "AT", "Profético",
         ("Isaías", "Isaías", "Isaías", "Is", "Isa"),
         "Isaías, filho de Amoz (com seções posteriores)",
         "Séc. VIII a.C.",
         "Juízo e consolação: o Santo de Israel, o servo sofredor e a nova criação."),
    Book("JER", "Jeremias", "AT", "Profético",
         ("Jeremias", "Jeremías", "Jr", "Jer"),
         "Jeremias (com auxílio de Baruque)",
         "Séc. VII–VI a.C.",
         "Juízo iminente sobre Judá e promessa de nova aliança."),
    Book("LAM", "Lamentações", "AT", "Poético/Sapiencial",
         ("Lamentações", "Lamentaciones", "Lm", "Lam"),
         "Jeremias (tradição)",
         "≈ 586 a.C.",
         "Luto pela queda de Jerusalém; esperança na fidelidade de Deus."),
    Book("EZK", "Ezequiel", "AT", "Profético",
         ("Ezequiel", "Ezequiel", "Ez", "Ezk"),
         "Ezequiel, sacerdote exilado",
         "593–571 a.C.",
         "A glória do Senhor no exílio: juízo, restauração e o novo templo."),
    Book("DAN", "Daniel", "AT", "Profético",
         ("Daniel", "Daniel", "Dn", "Dan"),
         "Daniel (tradição)",
         "Séc. VI a.C.; forma final no exílio/pós-exílio",
         "Soberania de Deus sobre os impérios; o Filho do homem e a ressurreição."),
    Book("HOS", "Oseias", "AT", "Profético",
         ("Oseias", "Oseas", "Os", "Hos"),
         "Oseias, filho de Beeri",
         "Séc. VIII a.C.",
         "O amor de Deus por Israel retratado no casamento do profeta."),
    Book("JOL", "Joel", "AT", "Profético",
         ("Joel", "Joel", "Jl", "Joe"),
         "Joel, filho de Petuel",
         "Séc. IX–V a.C. (incerto)",
         "O dia do Senhor: praga de gafanhotos, arrependimento e derramamento do Espírito."),
    Book("AMO", "Amós", "AT", "Profético",
         ("Amós", "Amos", "Am"),
         "Amós, pastor de Tecoa",
         "≈ 760–750 a.C.",
         "Justiça social e o juízo do Senhor sobre Israel."),
    Book("OBA", "Obadias", "AT", "Profético",
         ("Obadias", "Abdías", "Ob", "Oba"),
         "Obadias",
         "≈ séc. IX–VI a.C.",
         "Juízo sobre Edom e restauração de Israel."),
    Book("JON", "Jonas", "AT", "Profético",
         ("Jonas", "Jonás", "Jn", "Jon"),
         "Autor desconhecido (protagonista: Jonas)",
         "Séc. VIII a.C. (tradição)",
         "A misericórdia de Deus para Nínive e o contraste com o coração do profeta."),
    Book("MIC", "Miqueias", "AT", "Profético",
         ("Miqueias", "Miqueas", "Mq", "Mic"),
         "Miqueias de Moresete",
         "Séc. VIII a.C.",
         "Juízo, justiça e a promessa do governante de Belém."),
    Book("NAM", "Naum", "AT", "Profético",
         ("Naum", "Nahúm", "Na", "Nam"),
         "Naum",
         "≈ 663–612 a.C.",
         "Queda de Nínive: o Senhor vinga e é refúgio."),
    Book("HAB", "Habacuque", "AT", "Profético",
         ("Habacuque", "Habacuc", "Hc", "Hab"),
         "Habacuque",
         "≈ 609–598 a.C.",
         "O justo viverá pela fé: o problema do mal e a soberania divina."),
    Book("ZEP", "Sofonias", "AT", "Profético",
         ("Sofonias", "Sofonías", "Sf", "Zep"),
         "Sofonias",
         "≈ 640–609 a.C.",
         "O dia do Senhor: juízo universal e restauração do remanescente."),
    Book("HAG", "Ageu", "AT", "Profético",
         ("Ageu", "Hageo", "Ag", "Hag"),
         "Ageu",
         "≈ 520 a.C.",
         "Reconstrução do templo: buscai primeiro o reino."),
    Book("ZEC", "Zacarias", "AT", "Profético",
         ("Zacarias", "Zacarías", "Zc", "Zec"),
         "Zacarias",
         "520–518 a.C.",
         "Visões de restauração e o rei humilde que vem a Sião."),
    Book("MAL", "Malaquias", "AT", "Profético",
         ("Malaquias", "Malaquías", "Ml", "Mal"),
         "Malaquias",
         "≈ 450–430 a.C.",
         "Fidelidade no culto; o mensageiro que prepara o caminho do Senhor."),
    Book("MAT", "Mateus", "NT", "Evangelho",
         ("Mateus", "Mateo", "Matthew", "Mt", "Mat"),
         "Mateus, apóstolo e publicano",
         "≈ 60–70 d.C.",
         "Jesus como o Messias-Rei prometido; o evangelho do reino para Israel e nações."),
    Book("MRK", "Marcos", "NT", "Evangelho",
         ("Marcos", "Marcos", "Mc", "Mrk"),
         "João Marcos (associado a Pedro)",
         "≈ 55–65 d.C.",
         "Jesus, o Servo sofredor: ação, cruz e discipulado."),
    Book("LUK", "Lucas", "NT", "Evangelho",
         ("Lucas", "Lucas", "Lc", "Luk"),
         "Lucas, médico e companheiro de Paulo",
         "≈ 60–62 d.C.",
         "Investigação ordenada da vida de Jesus; salvação universal e do Espírito."),
    Book("JHN", "João", "NT", "Evangelho",
         ("João", "Juan", "John", "Jo", "Jh"),
         "João, filho de Zebedeu",
         "≈ 85–95 d.C.",
         "Jesus, o Verbo encarnado: sinais, 'EU SOU' e a vida eterna pela fé."),
    Book("ACT", "Atos", "NT", "Histórico",
         ("Atos", "Hechos", "Acts", "At", "Atos dos Apóstolos"),
         "Lucas",
         "≈ 62–65 d.C.",
         "A igreja de Jerusalém a Roma pelo poder do Espírito Santo."),
    Book("ROM", "Romanos", "NT", "Epístola Paulina",
         ("Romanos", "Romanos", "Rm", "Rom"),
         "Paulo",
         "≈ 57 d.C.",
         "O evangelho da justificação pela fé e suas implicações para a vida."),
    Book("1CO", "1 Coríntios", "NT", "Epístola Paulina",
         ("1 Coríntios", "I Corintios", "1Co", "1co", "1 corintios"),
         "Paulo (com Sóstenes)",
         "≈ 54–55 d.C.",
         "Correções na igreja de Corinto: divisões, moral, culto e ressurreição."),
    Book("2CO", "2 Coríntios", "NT", "Epístola Paulina",
         ("2 Coríntios", "II Corintios", "2Co", "2co", "2 corintios"),
         "Paulo",
         "≈ 55–56 d.C.",
         "Defesa do apostolado, consolação em Cristo e a coleta para Jerusalém."),
    Book("GAL", "Gálatas", "NT", "Epístola Paulina",
         ("Gálatas", "Gálatas", "Gl", "Gal"),
         "Paulo",
         "≈ 48–55 d.C.",
         "Justificação pela fé, não pelas obras da lei; liberdade em Cristo."),
    Book("EPH", "Efésios", "NT", "Epístola Paulina",
         ("Efésios", "Efesios", "Ef", "Eph"),
         "Paulo",
         "≈ 60–62 d.C.",
         "Os propósitos eternos de Deus em Cristo e a unidade da igreja."),
    Book("PHP", "Filipenses", "NT", "Epístola Paulina",
         ("Filipenses", "Filipenses", "Fp", "Php"),
         "Paulo (com Timóteo)",
         "≈ 61 d.C.",
         "Alegria no evangelho, humildade de Cristo e perseverança."),
    Book("COL", "Colossenses", "NT", "Epístola Paulina",
         ("Colossenses", "Colosenses", "Cl", "Col"),
         "Paulo (com Timóteo)",
         "≈ 60–62 d.C.",
         "A supremacia de Cristo sobre todo poder e a vida nova nele."),
    Book("1TH", "1 Tessalonicenses", "NT", "Epístola Paulina",
         ("1 Tessalonicenses", "I Tesalonicenses", "1Ts", "1ts", "1 tessalonicenses"),
         "Paulo (com Silvano e Timóteo)",
         "≈ 50–51 d.C.",
         "Santificação e esperança na volta de Cristo."),
    Book("2TH", "2 Tessalonicenses", "NT", "Epístola Paulina",
         ("2 Tessalonicenses", "II Tesalonicenses", "2Ts", "2ts", "2 tessalonicenses"),
         "Paulo (com Silvano e Timóteo)",
         "≈ 51–52 d.C.",
         "O dia do Senhor, o homem da iniquidade e o trabalho digno."),
    Book("1TI", "1 Timóteo", "NT", "Epístola Paulina",
         ("1 Timóteo", "I Timoteo", "1Tm", "1tm", "1 timoteo"),
         "Paulo",
         "≈ 62–64 d.C.",
         "Instruções à igreja e ao pastor: sã doutrina e vida piedosa."),
    Book("2TI", "2 Timóteo", "NT", "Epístola Paulina",
         ("2 Timóteo", "II Timoteo", "2Tm", "2tm", "2 timoteo"),
         "Paulo",
         "≈ 66–67 d.C.",
         "Última carta de Paulo: fidelidade à Escritura até o fim."),
    Book("TIT", "Tito", "NT", "Epístola Paulina",
         ("Tito", "Tito", "Tt", "Tit"),
         "Paulo",
         "≈ 63–65 d.C.",
         "Organização da igreja em Creta e o perfil do cristão."),
    Book("PHM", "Filemom", "NT", "Epístola Paulina",
         ("Filemom", "Filemón", "Fm", "Phm"),
         "Paulo (com Timóteo)",
         "≈ 60–62 d.C.",
         "Receber Onésimo como irmão: o evangelho transforma relações."),
    Book("HEB", "Hebreus", "NT", "Epístola Geral",
         ("Hebreus", "Hebreos", "Hb", "Heb"),
         "Autor anônimo (tradição paulina antiga, hoje incerto)",
         "≈ 60–70 d.C.",
         "A superioridade de Cristo: melhor sacerdote, sacrifício e aliança."),
    Book("JAS", "Tiago", "NT", "Epístola Geral",
         ("Tiago", "Santiago", "Tg", "Jam"),
         "Tiago, irmão do Senhor",
         "≈ 45–49 d.C.",
         "Fé viva que produz obras; sabedoria e domínio da língua."),
    Book("1PE", "1 Pedro", "NT", "Epístola Geral",
         ("1 Pedro", "I Pedro", "1Pe", "1pe", "1 pedro"),
         "Pedro (com Silvano)",
         "≈ 62–64 d.C.",
         "Esperança viva e santidade no sofrimento; pastoreio do rebanho."),
    Book("2PE", "2 Pedro", "NT", "Epístola Geral",
         ("2 Pedro", "II Pedro", "2Pe", "2pe", "2 pedro"),
         "Pedro",
         "≈ 64–67 d.C.",
         "Crescimento no conhecimento de Cristo e alerta contra falsos mestres."),
    Book("1JN", "1 João", "NT", "Epístola Geral",
         ("1 João", "I Juan", "1Jo", "1jo", "1 joao"),
         "João, o apóstolo",
         "≈ 85–95 d.C.",
         "Comunhão com Deus: luz, amor e verdade; certeza da vida eterna."),
    Book("2JN", "2 João", "NT", "Epístola Geral",
         ("2 João", "II Juan", "2Jo", "2jo", "2 joao"),
         "João, o apóstolo",
         "≈ 85–95 d.C.",
         "Andar na verdade e no amor; cuidado com os enganadores."),
    Book("3JN", "3 João", "NT", "Epístola Geral",
         ("3 João", "III Juan", "3Jo", "3jo", "3 joao"),
         "João, o apóstolo",
         "≈ 85–95 d.C.",
         "Hospitalidade e apoio aos obreiros; contraste com Diótrefes."),
    Book("JUD", "Judas", "NT", "Epístola Geral",
         ("Judas", "Judas", "Jd", "Jud"),
         "Judas, irmão de Tiago",
         "≈ 65–80 d.C.",
         "Batalhar pela fé contra falsos mestres."),
    Book("REV", "Apocalipse", "NT", "Profético",
         ("Apocalipse", "Apocalipsis", "Revelação", "Ap", "Rev"),
         "João",
         "≈ 90–96 d.C.",
         "Visões do trono, do Cordeiro e da vitória final; consolo aos que perseveram."),
)


BY_CODE: dict[str, Book] = {book.code: book for book in BOOKS}
BOOK_COUNT: int = len(BOOKS)


def all_profiles() -> list[BookProfile]:
    """Public profile list for the /api/bible/books endpoint."""
    return [
        BookProfile(
            code=book.code,
            name_pt=book.name_pt,
            testament=book.testament,
            genre=book.genre,
            author=book.author,
            date=book.date,
            occasion=book.occasion,
        )
        for book in BOOKS
    ]
